trigger:
- master

resources:
  repositories:

    - repository: PlaywrightRepo
      type: git
      name: AzureDemoGanesh/PlaywrightInit.git

stages:

- stage: PlaywrightJS
  displayName: Playwright JS Stage

  jobs:

  - job: RunPlaywrightTests
    displayName: Run Playwright Tests

    pool:
      vmImage: 'ubuntu-latest'

    steps:

    # Checkout Playwright Repo
    - checkout: PlaywrightRepo

    # Verify Folder Name
    - script: |
        echo "Repository Files"
        pwd
        ls -R $(Build.SourcesDirectory)
      displayName: Display Repository Files

    # Install Node.js
    - task: NodeTool@0
      displayName: Install Node.js

      inputs:
        versionSpec: '18.x'

    # Check Node Version
    - script: |
        node -v
        npm -v
      displayName: Check Node Version

    # Install NPM Packages
    - script: |
        npm install
      workingDirectory: '$(Build.SourcesDirectory)/PlaywrightInit'
      displayName: Install NPM Packages

    # Install Browsers
    - script: |
        npx playwright install --with-deps
      workingDirectory: '$(Build.SourcesDirectory)/PlaywrightInit'
      displayName: Install Playwright Browsers

    # Run Playwright Tests
    - script: |
        npx playwright test
      workingDirectory: '$(Build.SourcesDirectory)/PlaywrightInit'
      displayName: Run Playwright Tests

    # Publish Report
    - task: PublishPipelineArtifact@1
      displayName: Publish Playwright Report

      condition: always()

      inputs:
        targetPath: '$(Build.SourcesDirectory)/PlaywrightInit/playwright-report'
        artifact: 'playwright-report'
        publishLocation: 'pipeline'