trigger:
- master

resources:
  repositories:

    - repository: PlaywrightRepo
      type: git
      name: AzureDemoGanesh/PlaywrightInit.git

pool:
  vmImage: 'ubuntu-latest'

steps:

# Checkout Playwright Repo
- checkout: PlaywrightRepo

# Display Repository Structure
- script: |
    echo "Current Directory"
    pwd

    echo "Source Directory"
    ls -R $(Build.SourcesDirectory)
  displayName: Display Repository Files

# Install Node.js
- task: NodeTool@0
  displayName: Install Node.js

  inputs:
    versionSpec: '18.x'

# Verify Node.js
- script: |
    node -v
    npm -v
  displayName: Check Node Version

# Install NPM Packages
- script: |
    cd $(Build.SourcesDirectory)

    echo "Folders:"
    ls

    cd *

    echo "Inside Repo:"
    pwd
    ls

    npm install
  displayName: Install NPM Packages

# Install Playwright Browsers
- script: |
    cd $(Build.SourcesDirectory)
    cd *

    npx playwright install --with-deps
  displayName: Install Playwright Browsers

# Run Playwright Tests
- script: |
    cd $(Build.SourcesDirectory)
    cd *

    npx playwright test
  displayName: Run Playwright Tests

# Publish Playwright Report
- task: PublishPipelineArtifact@1
  displayName: Publish Playwright Report

  condition: always()

  inputs:
    targetPath: '$(Build.SourcesDirectory)/*/playwright-report'
    artifact: 'playwright-report'
    publishLocation: 'pipeline'